# ============================================================
# 02_rq1_overlap_and_shared_core.R
#
# Purpose:
# Calculate RQ1 global overlap and matched-city shared-core
# summaries for sewage and transit resistomes.
#
# Input:
# Corrected combined binary matrices generated by:
# 01_build_rq1_binary_matrices.R
#
# Expected matrix orientation:
# Rows    = city-environment profiles
# Columns = ARG features
#
# Example profile names:
# Berlin_Sewage
# Berlin_Transit
# Rio_de_Janeiro_Sewage
# Rio_de_Janeiro_Transit
#
# Main outputs:
# - global overlap summary
# - feature-level overlap classification
# - shared, sewage-only, and transit-only feature lists
# - matched-city shared-core threshold summaries
# - city-level shared feature summaries
# ============================================================

# ------------------------------------------------------------
# 1. User-adjustable settings
# ------------------------------------------------------------

input_dir <- file.path(
  "results",
  "rq1",
  "matrices"
)

output_dir <- file.path(
  "results",
  "rq1",
  "overlap_core"
)

expected_number_of_cities <- 16

shared_core_thresholds <- c(
  "100_percent" = 1.00,
  "75_percent" = 0.75,
  "50_percent" = 0.50
)

group_matrix_file <- file.path(
  input_dir,
  "rq1_group_combined_binary_matrix.tsv"
)

class_matrix_file <- file.path(
  input_dir,
  "rq1_class_combined_binary_matrix.tsv"
)

# ------------------------------------------------------------
# 2. Create output directory
# ------------------------------------------------------------

if (!dir.exists(output_dir)) {
  dir.create(
    output_dir,
    recursive = TRUE
  )
}

# ------------------------------------------------------------
# 3. Helper function: read combined binary matrix
# ------------------------------------------------------------

read_combined_binary_matrix <- function(file_path, level_name) {

  if (!file.exists(file_path)) {
    stop(
      paste0(
        level_name,
        " combined matrix not found:\n",
        file_path
      )
    )
  }

  message(
    "\nReading ",
    level_name,
    " combined matrix:\n",
    file_path
  )

  raw_df <- read.delim(
    file = file_path,
    header = TRUE,
    sep = "\t",
    check.names = FALSE,
    stringsAsFactors = FALSE,
    quote = "",
    comment.char = ""
  )

  if (ncol(raw_df) < 2) {
    stop(
      paste0(
        level_name,
        " matrix must contain one profile column and at least one feature column."
      )
    )
  }

  profile_ids <- trimws(
    as.character(raw_df[[1]])
  )

  if (any(is.na(profile_ids)) || any(profile_ids == "")) {
    stop(
      paste0(
        level_name,
        " matrix contains missing or empty profile names in the first column."
      )
    )
  }

  value_df <- raw_df[
    ,
    -1,
    drop = FALSE
  ]

  value_df[] <- lapply(
    value_df,
    function(x) {
      suppressWarnings(
        as.numeric(x)
      )
    }
  )

  value_matrix <- as.matrix(
    value_df
  )

  rownames(value_matrix) <- profile_ids

  if (any(is.na(value_matrix))) {
    stop(
      paste0(
        level_name,
        " matrix contains missing or non-numeric values."
      )
    )
  }

  value_matrix <- ifelse(
    value_matrix > 0,
    1,
    0
  )

  storage.mode(value_matrix) <- "numeric"

  if (any(duplicated(rownames(value_matrix)))) {
    stop(
      paste0(
        level_name,
        " matrix contains duplicated profile names."
      )
    )
  }

  if (any(duplicated(colnames(value_matrix)))) {
    stop(
      paste0(
        level_name,
        " matrix contains duplicated feature names."
      )
    )
  }

  message(
    level_name,
    ": ",
    nrow(value_matrix),
    " profiles × ",
    ncol(value_matrix),
    " features"
  )

  return(value_matrix)
}

# ------------------------------------------------------------
# 4. Helper function: build metadata from profile names
# ------------------------------------------------------------

build_profile_metadata <- function(binary_matrix, level_name) {

  metadata <- data.frame(
    Profile = rownames(binary_matrix),
    stringsAsFactors = FALSE
  )

  metadata$Environment <- sub(
    "^.*_(Sewage|Transit)$",
    "\\1",
    metadata$Profile
  )

  metadata$City <- sub(
    "_(Sewage|Transit)$",
    "",
    metadata$Profile
  )

  if (!all(metadata$Environment %in% c("Sewage", "Transit"))) {
    stop(
      paste0(
        level_name,
        ": environment could not be extracted from some profile names:\n",
        paste(metadata$Profile, collapse = "\n")
      )
    )
  }

  metadata$Environment <- factor(
    metadata$Environment,
    levels = c(
      "Sewage",
      "Transit"
    )
  )

  rownames(metadata) <- metadata$Profile

  city_environment_table <- table(
    metadata$City,
    metadata$Environment
  )

  if (!all(city_environment_table == 1)) {
    print(
      city_environment_table
    )

    stop(
      paste0(
        level_name,
        ": each city must have exactly one sewage and one transit profile."
      )
    )
  }

  if (length(unique(metadata$City)) != expected_number_of_cities) {
    warning(
      paste0(
        level_name,
        ": expected ",
        expected_number_of_cities,
        " matched cities, but found ",
        length(unique(metadata$City)),
        "."
      )
    )
  }

  metadata <- metadata[
    order(
      metadata$City,
      metadata$Environment
    ),
    ,
    drop = FALSE
  ]

  return(metadata)
}

# ------------------------------------------------------------
# 5. Helper function: write feature list
# ------------------------------------------------------------

write_feature_list <- function(feature_vector, file_path) {

  output_df <- data.frame(
    Feature = sort(feature_vector),
    stringsAsFactors = FALSE
  )

  write.table(
    output_df,
    file = file_path,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )
}

# ------------------------------------------------------------
# 6. Main function: overlap and shared-core analysis
# ------------------------------------------------------------

run_overlap_and_core_analysis <- function(
  matrix_file,
  level_name,
  output_prefix
) {

  message(
    "\n============================================================"
  )

  message(
    "Running RQ1 overlap and shared-core analysis: ",
    level_name
  )

  message(
    "============================================================"
  )

  binary_matrix <- read_combined_binary_matrix(
    file_path = matrix_file,
    level_name = level_name
  )

  metadata <- build_profile_metadata(
    binary_matrix = binary_matrix,
    level_name = level_name
  )

  binary_matrix <- binary_matrix[
    metadata$Profile,
    ,
    drop = FALSE
  ]

  cities <- sort(
    unique(metadata$City)
  )

  number_of_cities <- length(cities)

  sewage_profiles <- metadata$Profile[
    metadata$Environment == "Sewage"
  ]

  transit_profiles <- metadata$Profile[
    metadata$Environment == "Transit"
  ]

  sewage_matrix <- binary_matrix[
    sewage_profiles,
    ,
    drop = FALSE
  ]

  transit_matrix <- binary_matrix[
    transit_profiles,
    ,
    drop = FALSE
  ]

  sewage_cities <- metadata[
    sewage_profiles,
    "City"
  ]

  transit_cities <- metadata[
    transit_profiles,
    "City"
  ]

  sewage_matrix <- sewage_matrix[
    order(sewage_cities),
    ,
    drop = FALSE
  ]

  transit_matrix <- transit_matrix[
    order(transit_cities),
    ,
    drop = FALSE
  ]

  rownames(sewage_matrix) <- sort(sewage_cities)
  rownames(transit_matrix) <- sort(transit_cities)

  if (!identical(rownames(sewage_matrix), rownames(transit_matrix))) {
    stop(
      paste0(
        level_name,
        ": sewage and transit city order does not match."
      )
    )
  }

  # ----------------------------------------------------------
  # 6.1 Global environment-level overlap
  # ----------------------------------------------------------

  sewage_city_count <- colSums(
    sewage_matrix
  )

  transit_city_count <- colSums(
    transit_matrix
  )

  present_in_sewage <- sewage_city_count > 0
  present_in_transit <- transit_city_count > 0

  shared_features <- names(
    present_in_sewage
  )[
    present_in_sewage & present_in_transit
  ]

  sewage_only_features <- names(
    present_in_sewage
  )[
    present_in_sewage & !present_in_transit
  ]

  transit_only_features <- names(
    present_in_transit
  )[
    !present_in_sewage & present_in_transit
  ]

  feature_classification <- ifelse(
    present_in_sewage & present_in_transit,
    "Shared",
    ifelse(
      present_in_sewage & !present_in_transit,
      "Sewage_only",
      ifelse(
        !present_in_sewage & present_in_transit,
        "Transit_only",
        "Absent"
      )
    )
  )

  feature_overlap_df <- data.frame(
    Feature = colnames(binary_matrix),
    Sewage_city_count = sewage_city_count,
    Transit_city_count = transit_city_count,
    Sewage_prevalence = sewage_city_count / number_of_cities,
    Transit_prevalence = transit_city_count / number_of_cities,
    Present_in_sewage = present_in_sewage,
    Present_in_transit = present_in_transit,
    Classification = feature_classification,
    stringsAsFactors = FALSE
  )

  feature_overlap_df <- feature_overlap_df[
    order(
      feature_overlap_df$Classification,
      feature_overlap_df$Feature
    ),
    ,
    drop = FALSE
  ]

  total_features <- ncol(binary_matrix)
  sewage_detected <- sum(present_in_sewage)
  transit_detected <- sum(present_in_transit)
  shared_count <- length(shared_features)
  sewage_only_count <- length(sewage_only_features)
  transit_only_count <- length(transit_only_features)

  global_overlap_summary <- data.frame(
    Level = level_name,
    Matched_cities = number_of_cities,
    Total_retained_features = total_features,
    Sewage_detected_features = sewage_detected,
    Transit_detected_features = transit_detected,
    Shared_features = shared_count,
    Sewage_only_features = sewage_only_count,
    Transit_only_features = transit_only_count,
    Shared_fraction_of_all_features = shared_count / total_features,
    Shared_fraction_of_sewage_features = shared_count / sewage_detected,
    Shared_fraction_of_transit_features = shared_count / transit_detected,
    stringsAsFactors = FALSE
  )

  message(
    "\nGlobal overlap summary:"
  )

  print(
    global_overlap_summary
  )

  # ----------------------------------------------------------
  # 6.2 Matched-city shared-core analysis
  #
  # A feature is counted for a city when it is present in both
  # sewage and transit for that same city.
  # ----------------------------------------------------------

  shared_by_city_matrix <- sewage_matrix * transit_matrix

  matched_city_shared_count <- colSums(
    shared_by_city_matrix
  )

  matched_city_shared_fraction <- matched_city_shared_count / number_of_cities

  shared_core_df <- data.frame(
    Feature = colnames(binary_matrix),
    Sewage_city_count = sewage_city_count,
    Transit_city_count = transit_city_count,
    Matched_city_shared_count = matched_city_shared_count,
    Matched_city_shared_fraction = matched_city_shared_fraction,
    Global_classification = feature_classification,
    stringsAsFactors = FALSE
  )

  shared_core_df <- shared_core_df[
    order(
      -shared_core_df$Matched_city_shared_count,
      shared_core_df$Feature
    ),
    ,
    drop = FALSE
  ]

  threshold_summary_list <- list()

  for (threshold_name in names(shared_core_thresholds)) {

    threshold_value <- shared_core_thresholds[[threshold_name]]

    minimum_city_count <- ceiling(
      threshold_value * number_of_cities
    )

    retained_at_threshold <- shared_core_df[
      shared_core_df$Matched_city_shared_count >= minimum_city_count,
      ,
      drop = FALSE
    ]

    threshold_summary_list[[threshold_name]] <- data.frame(
      Level = level_name,
      Threshold_name = threshold_name,
      Threshold_fraction = threshold_value,
      Minimum_matched_city_count = minimum_city_count,
      Number_of_features = nrow(retained_at_threshold),
      stringsAsFactors = FALSE
    )

    threshold_feature_output <- file.path(
      output_dir,
      paste0(
        output_prefix,
        "_shared_core_features_",
        threshold_name,
        ".tsv"
      )
    )

    write.table(
      retained_at_threshold,
      file = threshold_feature_output,
      sep = "\t",
      quote = FALSE,
      row.names = FALSE
    )
  }

  shared_core_threshold_summary <- do.call(
    rbind,
    threshold_summary_list
  )

  rownames(shared_core_threshold_summary) <- NULL

  message(
    "\nShared-core threshold summary:"
  )

  print(
    shared_core_threshold_summary
  )

  # ----------------------------------------------------------
  # 6.3 City-level shared feature summaries
  # ----------------------------------------------------------

  city_level_summary <- data.frame(
    City = rownames(sewage_matrix),
    Sewage_feature_richness = rowSums(sewage_matrix),
    Transit_feature_richness = rowSums(transit_matrix),
    Shared_feature_count = rowSums(shared_by_city_matrix),
    stringsAsFactors = FALSE
  )

  city_level_summary$Jaccard_similarity <- with(
    city_level_summary,
    Shared_feature_count /
      (
        Sewage_feature_richness +
          Transit_feature_richness -
          Shared_feature_count
      )
  )

  city_level_summary <- city_level_summary[
    order(
      -city_level_summary$Shared_feature_count,
      city_level_summary$City
    ),
    ,
    drop = FALSE
  ]

  # ----------------------------------------------------------
  # 6.4 Write outputs
  # ----------------------------------------------------------

  global_overlap_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_global_overlap_summary.tsv"
    )
  )

  feature_overlap_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_feature_overlap_classification.tsv"
    )
  )

  shared_features_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_shared_features.tsv"
    )
  )

  sewage_only_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_sewage_only_features.tsv"
    )
  )

  transit_only_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_transit_only_features.tsv"
    )
  )

  shared_core_feature_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_matched_city_shared_core_by_feature.tsv"
    )
  )

  shared_core_threshold_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_shared_core_threshold_summary.tsv"
    )
  )

  city_level_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_city_level_shared_feature_summary.tsv"
    )
  )

  write.table(
    global_overlap_summary,
    file = global_overlap_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    feature_overlap_df,
    file = feature_overlap_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write_feature_list(
    feature_vector = shared_features,
    file_path = shared_features_output
  )

  write_feature_list(
    feature_vector = sewage_only_features,
    file_path = sewage_only_output
  )

  write_feature_list(
    feature_vector = transit_only_features,
    file_path = transit_only_output
  )

  write.table(
    shared_core_df,
    file = shared_core_feature_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    shared_core_threshold_summary,
    file = shared_core_threshold_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    city_level_summary,
    file = city_level_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  message(
    "\nFiles written for ",
    level_name,
    ":"
  )

  message(global_overlap_output)
  message(feature_overlap_output)
  message(shared_features_output)
  message(sewage_only_output)
  message(transit_only_output)
  message(shared_core_feature_output)
  message(shared_core_threshold_output)
  message(city_level_output)

  return(
    list(
      global_overlap_summary = global_overlap_summary,
      feature_overlap = feature_overlap_df,
      shared_core = shared_core_df,
      shared_core_threshold_summary = shared_core_threshold_summary,
      city_level_summary = city_level_summary
    )
  )
}

# ------------------------------------------------------------
# 7. Run ARG Group analysis
# ------------------------------------------------------------

group_results <- run_overlap_and_core_analysis(
  matrix_file = group_matrix_file,
  level_name = "ARG Group",
  output_prefix = "rq1_group"
)

# ------------------------------------------------------------
# 8. Run Resistance Class analysis
# ------------------------------------------------------------

class_results <- run_overlap_and_core_analysis(
  matrix_file = class_matrix_file,
  level_name = "Resistance Class",
  output_prefix = "rq1_class"
)

# ------------------------------------------------------------
# 9. Save combined summaries
# ------------------------------------------------------------

combined_global_summary <- rbind(
  group_results$global_overlap_summary,
  class_results$global_overlap_summary
)

combined_threshold_summary <- rbind(
  group_results$shared_core_threshold_summary,
  class_results$shared_core_threshold_summary
)

combined_global_output <- file.path(
  output_dir,
  "rq1_combined_global_overlap_summary.tsv"
)

combined_threshold_output <- file.path(
  output_dir,
  "rq1_combined_shared_core_threshold_summary.tsv"
)

write.table(
  combined_global_summary,
  file = combined_global_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  combined_threshold_summary,
  file = combined_threshold_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

message(
  "\n============================================================"
)

message(
  "RQ1 overlap and shared-core analysis completed."
)

message(
  "Combined global summary:"
)

message(
  combined_global_output
)

message(
  "Combined shared-core threshold summary:"
)

message(
  combined_threshold_output
)

message(
  "============================================================"
)
