# ============================================================
# 03_rq1_jaccard_pcoa_permanova.R
#
# Purpose:
# Perform RQ1 Jaccard-based compositional analysis for sewage
# and transit resistomes.
#
# This script:
# 1. Reads corrected combined binary matrices generated by:
#    01_build_rq1_binary_matrices.R
# 2. Calculates binary Jaccard distance matrices.
# 3. Performs PCoA using cmdscale.
# 4. Performs city-restricted PERMANOVA.
# 5. Performs PERMDISP using betadisper/permutest.
#
# Input matrix orientation:
# Rows    = city-environment profiles
# Columns = ARG features
#
# Example profile names:
# Berlin_Sewage
# Berlin_Transit
#
# Main outputs:
# results/rq1/ordination_stats/
# ============================================================

# ------------------------------------------------------------
# 1. Required packages
# ------------------------------------------------------------

required_packages <- c(
  "vegan"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    FUN.VALUE = logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste0(
      "The following required R packages are missing:\n",
      paste(missing_packages, collapse = ", "),
      "\nInstall them before running this script."
    )
  )
}

library(vegan)

# ------------------------------------------------------------
# 2. User-adjustable settings
# ------------------------------------------------------------

input_dir <- file.path(
  "results",
  "rq1",
  "matrices"
)

output_dir <- file.path(
  "results",
  "rq1",
  "ordination_stats"
)

expected_number_of_cities <- 16

permanova_permutations <- 9999
permdisp_permutations <- 999

group_matrix_file <- file.path(
  input_dir,
  "rq1_group_combined_binary_matrix.tsv"
)

class_matrix_file <- file.path(
  input_dir,
  "rq1_class_combined_binary_matrix.tsv"
)

if (!dir.exists(output_dir)) {
  dir.create(
    output_dir,
    recursive = TRUE
  )
}

# ------------------------------------------------------------
# 3. Check required input files
# ------------------------------------------------------------

required_input_files <- c(
  group_matrix_file,
  class_matrix_file
)

missing_input_files <- required_input_files[
  !file.exists(required_input_files)
]

if (length(missing_input_files) > 0) {
  stop(
    paste0(
      "The following required input files are missing:\n",
      paste(missing_input_files, collapse = "\n")
    )
  )
}

# ------------------------------------------------------------
# 4. Helper function: read combined binary matrix
# ------------------------------------------------------------

read_combined_binary_matrix <- function(file_path, level_name) {

  message(
    "\nReading ",
    level_name,
    " combined binary matrix:\n",
    file_path
  )

  raw_df <- read.delim(
    file = file_path,
    header = TRUE,
    sep = "\t",
    check.names = FALSE,
    stringsAsFactors = FALSE,
    quote = "",
    comment.char = ""
  )

  if (ncol(raw_df) < 2) {
    stop(
      paste0(
        level_name,
        ": matrix must contain one profile column and at least one feature column."
      )
    )
  }

  profile_ids <- trimws(
    as.character(raw_df[[1]])
  )

  if (any(is.na(profile_ids)) || any(profile_ids == "")) {
    stop(
      paste0(
        level_name,
        ": missing or empty profile names detected in the first column."
      )
    )
  }

  value_df <- raw_df[
    ,
    -1,
    drop = FALSE
  ]

  value_df[] <- lapply(
    value_df,
    function(x) {
      suppressWarnings(
        as.numeric(x)
      )
    }
  )

  value_matrix <- as.matrix(
    value_df
  )

  rownames(value_matrix) <- profile_ids

  if (any(is.na(value_matrix))) {
    stop(
      paste0(
        level_name,
        ": matrix contains missing or non-numeric values."
      )
    )
  }

  value_matrix <- ifelse(
    value_matrix > 0,
    1,
    0
  )

  storage.mode(value_matrix) <- "numeric"

  if (any(duplicated(rownames(value_matrix)))) {
    stop(
      paste0(
        level_name,
        ": duplicated profile names detected."
      )
    )
  }

  if (any(duplicated(colnames(value_matrix)))) {
    stop(
      paste0(
        level_name,
        ": duplicated feature names detected."
      )
    )
  }

  if (any(rowSums(value_matrix) == 0)) {
    stop(
      paste0(
        level_name,
        ": one or more profiles contain zero detected features."
      )
    )
  }

  message(
    level_name,
    ": ",
    nrow(value_matrix),
    " profiles × ",
    ncol(value_matrix),
    " features"
  )

  return(value_matrix)
}

# ------------------------------------------------------------
# 5. Helper function: build profile metadata
# ------------------------------------------------------------

build_profile_metadata <- function(binary_matrix, level_name) {

  metadata <- data.frame(
    Profile = rownames(binary_matrix),
    stringsAsFactors = FALSE
  )

  metadata$Environment <- sub(
    "^.*_(Sewage|Transit)$",
    "\\1",
    metadata$Profile
  )

  metadata$City <- sub(
    "_(Sewage|Transit)$",
    "",
    metadata$Profile
  )

  if (!all(metadata$Environment %in% c("Sewage", "Transit"))) {
    stop(
      paste0(
        level_name,
        ": environment could not be extracted from some profile names:\n",
        paste(metadata$Profile, collapse = "\n")
      )
    )
  }

  metadata$Environment <- factor(
    metadata$Environment,
    levels = c(
      "Sewage",
      "Transit"
    )
  )

  rownames(metadata) <- metadata$Profile

  city_environment_table <- table(
    metadata$City,
    metadata$Environment
  )

  if (!all(city_environment_table == 1)) {
    print(
      city_environment_table
    )

    stop(
      paste0(
        level_name,
        ": each city must contain exactly one sewage and one transit profile."
      )
    )
  }

  if (length(unique(metadata$City)) != expected_number_of_cities) {
    warning(
      paste0(
        level_name,
        ": expected ",
        expected_number_of_cities,
        " matched cities, but found ",
        length(unique(metadata$City)),
        "."
      )
    )
  }

  metadata <- metadata[
    order(
      metadata$City,
      metadata$Environment
    ),
    ,
    drop = FALSE
  ]

  return(metadata)
}

# ------------------------------------------------------------
# 6. Helper function: write distance matrix
# ------------------------------------------------------------

write_distance_matrix <- function(distance_object, file_path) {

  distance_matrix <- as.matrix(
    distance_object
  )

  output_df <- data.frame(
    Profile = rownames(distance_matrix),
    distance_matrix,
    check.names = FALSE
  )

  write.table(
    output_df,
    file = file_path,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )
}

# ------------------------------------------------------------
# 7. Helper function: convert anova-like table to data frame
# ------------------------------------------------------------

anova_to_df <- function(x) {

  output_df <- as.data.frame(
    x
  )

  output_df$Term <- rownames(
    output_df
  )

  output_df <- output_df[
    ,
    c(
      "Term",
      setdiff(
        colnames(output_df),
        "Term"
      )
    ),
    drop = FALSE
  ]

  rownames(output_df) <- NULL

  return(output_df)
}

# ------------------------------------------------------------
# 8. Main function: Jaccard, PCoA, PERMANOVA, PERMDISP
# ------------------------------------------------------------

run_rq1_ordination_stats <- function(
  matrix_file,
  level_name,
  output_prefix
) {

  message(
    "\n============================================================"
  )

  message(
    "Running RQ1 ordination and statistical analysis: ",
    level_name
  )

  message(
    "============================================================"
  )

  binary_matrix <- read_combined_binary_matrix(
    file_path = matrix_file,
    level_name = level_name
  )

  metadata <- build_profile_metadata(
    binary_matrix = binary_matrix,
    level_name = level_name
  )

  binary_matrix <- binary_matrix[
    metadata$Profile,
    ,
    drop = FALSE
  ]

  # ----------------------------------------------------------
  # 8.1 Calculate binary Jaccard distance
  # ----------------------------------------------------------

  jaccard_dist <- vegan::vegdist(
    binary_matrix,
    method = "jaccard",
    binary = TRUE
  )

  jaccard_matrix <- as.matrix(
    jaccard_dist
  )

  if (max(abs(jaccard_matrix - t(jaccard_matrix))) > 1e-10) {
    stop(
      paste0(
        level_name,
        ": Jaccard distance matrix is not symmetric."
      )
    )
  }

  if (max(abs(diag(jaccard_matrix))) > 1e-10) {
    stop(
      paste0(
        level_name,
        ": Jaccard distance matrix diagonal is not zero."
      )
    )
  }

  if (any(jaccard_matrix < 0) || any(jaccard_matrix > 1)) {
    stop(
      paste0(
        level_name,
        ": Jaccard distance values should lie between 0 and 1."
      )
    )
  }

  # ----------------------------------------------------------
  # 8.2 PCoA using cmdscale
  # ----------------------------------------------------------

  pcoa_result <- stats::cmdscale(
    jaccard_dist,
    k = 2,
    eig = TRUE
  )

  pcoa_eigenvalues <- pcoa_result$eig

  positive_eigenvalues <- pcoa_eigenvalues[
    pcoa_eigenvalues > 0
  ]

  pcoa1_percent <- 100 *
    pcoa_eigenvalues[1] /
    sum(positive_eigenvalues)

  pcoa2_percent <- 100 *
    pcoa_eigenvalues[2] /
    sum(positive_eigenvalues)

  negative_eigenvalues <- pcoa_eigenvalues[
    pcoa_eigenvalues < 0
  ]

  eigenvalue_summary <- data.frame(
    Level = level_name,
    Number_of_profiles = nrow(binary_matrix),
    Number_of_features = ncol(binary_matrix),
    Number_of_positive_eigenvalues = sum(pcoa_eigenvalues > 0),
    Number_of_negative_eigenvalues = sum(pcoa_eigenvalues < 0),
    Sum_positive_eigenvalues = sum(pcoa_eigenvalues[pcoa_eigenvalues > 0]),
    Sum_absolute_negative_eigenvalues = sum(abs(negative_eigenvalues)),
    Most_negative_eigenvalue = ifelse(
      length(negative_eigenvalues) > 0,
      min(negative_eigenvalues),
      0
    ),
    Negative_inertia_relative_to_positive_inertia = ifelse(
      sum(pcoa_eigenvalues[pcoa_eigenvalues > 0]) > 0,
      sum(abs(negative_eigenvalues)) /
        sum(pcoa_eigenvalues[pcoa_eigenvalues > 0]),
      NA
    ),
    PCoA1_percent_positive_inertia = pcoa1_percent,
    PCoA2_percent_positive_inertia = pcoa2_percent,
    stringsAsFactors = FALSE
  )

  pcoa_coordinates <- data.frame(
    Profile = rownames(binary_matrix),
    City = metadata$City,
    Environment = metadata$Environment,
    PCoA1 = pcoa_result$points[
      ,
      1
    ],
    PCoA2 = pcoa_result$points[
      ,
      2
    ],
    stringsAsFactors = FALSE
  )

  eigenvalue_df <- data.frame(
    Axis = seq_along(
      pcoa_eigenvalues
    ),
    Eigenvalue = pcoa_eigenvalues,
    Positive = pcoa_eigenvalues > 0,
    stringsAsFactors = FALSE
  )

  # ----------------------------------------------------------
  # 8.3 City-restricted PERMANOVA
  #
  # The formula tests the effect of environment while restricting
  # permutations within matched city blocks.
  # ----------------------------------------------------------

  set.seed(123)

  permanova_result <- vegan::adonis2(
    jaccard_dist ~ Environment,
    data = metadata,
    permutations = permanova_permutations,
    strata = metadata$City
  )

  permanova_df <- anova_to_df(
    permanova_result
  )

  permanova_df$Level <- level_name
  permanova_df$Permutation_design <- "Restricted within city"
  permanova_df$Permutations <- permanova_permutations

  permanova_df <- permanova_df[
    ,
    c(
      "Level",
      "Permutation_design",
      "Permutations",
      setdiff(
        colnames(permanova_df),
        c(
          "Level",
          "Permutation_design",
          "Permutations"
        )
      )
    ),
    drop = FALSE
  ]

  # ----------------------------------------------------------
  # 8.4 PERMDISP
  #
  # Tests whether multivariate dispersion differs between
  # sewage and transit profiles.
  # ----------------------------------------------------------

  betadisper_result <- vegan::betadisper(
    jaccard_dist,
    group = metadata$Environment
  )

  set.seed(123)

  permdisp_result <- vegan::permutest(
    betadisper_result,
    permutations = permdisp_permutations
  )

  permdisp_df <- anova_to_df(
    permdisp_result$tab
  )

  permdisp_df$Level <- level_name
  permdisp_df$Permutation_design <- "Unrestricted"
  permdisp_df$Permutations <- permdisp_permutations

  permdisp_df <- permdisp_df[
    ,
    c(
      "Level",
      "Permutation_design",
      "Permutations",
      setdiff(
        colnames(permdisp_df),
        c(
          "Level",
          "Permutation_design",
          "Permutations"
        )
      )
    ),
    drop = FALSE
  ]

  dispersion_distances <- data.frame(
    Profile = metadata$Profile,
    City = metadata$City,
    Environment = metadata$Environment,
    Distance_to_group_centroid = betadisper_result$distances,
    stringsAsFactors = FALSE
  )

  dispersion_group_summary <- aggregate(
    Distance_to_group_centroid ~ Environment,
    data = dispersion_distances,
    FUN = function(x) {
      c(
        n = length(x),
        mean = mean(x),
        median = median(x),
        sd = stats::sd(x),
        min = min(x),
        max = max(x)
      )
    }
  )

  dispersion_group_summary <- do.call(
    data.frame,
    dispersion_group_summary
  )

  colnames(dispersion_group_summary) <- c(
    "Environment",
    "n",
    "mean_distance_to_centroid",
    "median_distance_to_centroid",
    "sd_distance_to_centroid",
    "min_distance_to_centroid",
    "max_distance_to_centroid"
  )

  dispersion_group_summary$Level <- level_name

  dispersion_group_summary <- dispersion_group_summary[
    ,
    c(
      "Level",
      "Environment",
      "n",
      "mean_distance_to_centroid",
      "median_distance_to_centroid",
      "sd_distance_to_centroid",
      "min_distance_to_centroid",
      "max_distance_to_centroid"
    )
  ]

  # ----------------------------------------------------------
  # 8.5 Write outputs
  # ----------------------------------------------------------

  distance_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_jaccard_distance_matrix.tsv"
    )
  )

  pcoa_coordinates_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_pcoa_coordinates.tsv"
    )
  )

  eigenvalue_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_pcoa_eigenvalues.tsv"
    )
  )

  eigenvalue_summary_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_pcoa_eigenvalue_summary.tsv"
    )
  )

  permanova_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_city_restricted_permanova.tsv"
    )
  )

  permdisp_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_permdisp_permutest.tsv"
    )
  )

  dispersion_distances_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_permdisp_distances_to_centroid.tsv"
    )
  )

  dispersion_summary_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_permdisp_group_summary.tsv"
    )
  )

  metadata_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_ordination_metadata.tsv"
    )
  )

  write_distance_matrix(
    distance_object = jaccard_dist,
    file_path = distance_output
  )

  write.table(
    pcoa_coordinates,
    file = pcoa_coordinates_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    eigenvalue_df,
    file = eigenvalue_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    eigenvalue_summary,
    file = eigenvalue_summary_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    permanova_df,
    file = permanova_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    permdisp_df,
    file = permdisp_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    dispersion_distances,
    file = dispersion_distances_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    dispersion_group_summary,
    file = dispersion_summary_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    metadata,
    file = metadata_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  message(
    "\nPCoA axis percentages for ",
    level_name,
    ":"
  )

  message(
    "PCoA1 = ",
    round(pcoa1_percent, 3),
    "%"
  )

  message(
    "PCoA2 = ",
    round(pcoa2_percent, 3),
    "%"
  )

  message(
    "\nPERMANOVA result for ",
    level_name,
    ":"
  )

  print(
    permanova_result
  )

  message(
    "\nPERMDISP result for ",
    level_name,
    ":"
  )

  print(
    permdisp_result
  )

  message(
    "\nFiles written for ",
    level_name,
    ":"
  )

  message(distance_output)
  message(pcoa_coordinates_output)
  message(eigenvalue_output)
  message(eigenvalue_summary_output)
  message(permanova_output)
  message(permdisp_output)
  message(dispersion_distances_output)
  message(dispersion_summary_output)
  message(metadata_output)

  return(
    list(
      distance = jaccard_dist,
      metadata = metadata,
      pcoa_coordinates = pcoa_coordinates,
      eigenvalue_summary = eigenvalue_summary,
      permanova = permanova_df,
      permdisp = permdisp_df,
      dispersion_distances = dispersion_distances,
      dispersion_group_summary = dispersion_group_summary
    )
  )
}

# ------------------------------------------------------------
# 9. Run ARG Group analysis
# ------------------------------------------------------------

group_results <- run_rq1_ordination_stats(
  matrix_file = group_matrix_file,
  level_name = "ARG Group",
  output_prefix = "rq1_group"
)

# ------------------------------------------------------------
# 10. Run Resistance Class analysis
# ------------------------------------------------------------

class_results <- run_rq1_ordination_stats(
  matrix_file = class_matrix_file,
  level_name = "Resistance Class",
  output_prefix = "rq1_class"
)

# ------------------------------------------------------------
# 11. Save combined summaries
# ------------------------------------------------------------

combined_eigenvalue_summary <- rbind(
  group_results$eigenvalue_summary,
  class_results$eigenvalue_summary
)

combined_permanova_summary <- rbind(
  group_results$permanova,
  class_results$permanova
)

combined_permdisp_summary <- rbind(
  group_results$permdisp,
  class_results$permdisp
)

combined_dispersion_summary <- rbind(
  group_results$dispersion_group_summary,
  class_results$dispersion_group_summary
)

combined_eigenvalue_output <- file.path(
  output_dir,
  "rq1_combined_pcoa_eigenvalue_summary.tsv"
)

combined_permanova_output <- file.path(
  output_dir,
  "rq1_combined_city_restricted_permanova.tsv"
)

combined_permdisp_output <- file.path(
  output_dir,
  "rq1_combined_permdisp_permutest.tsv"
)

combined_dispersion_output <- file.path(
  output_dir,
  "rq1_combined_permdisp_group_summary.tsv"
)

write.table(
  combined_eigenvalue_summary,
  file = combined_eigenvalue_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  combined_permanova_summary,
  file = combined_permanova_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  combined_permdisp_summary,
  file = combined_permdisp_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  combined_dispersion_summary,
  file = combined_dispersion_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

message(
  "\n============================================================"
)

message(
  "RQ1 Jaccard, PCoA, PERMANOVA, and PERMDISP analysis completed."
)

message(
  "Combined outputs:"
)

message(combined_eigenvalue_output)
message(combined_permanova_output)
message(combined_permdisp_output)
message(combined_dispersion_output)

message(
  "============================================================"
)
