# ============================================================
# 04_rq1_within_between_city_similarity.R
#
# Purpose:
# Compare sewage-transit Jaccard similarity for:
# 1. within-city pairs
# 2. between-city pairs
#
# This is a descriptive RQ1 analysis showing whether sewage and
# transit profiles from the same city are more similar than
# sewage-transit profiles from different cities.
#
# Input:
# Jaccard distance matrices generated by:
# 03_rq1_jaccard_pcoa_permanova.R
#
# Expected input files:
# results/rq1/ordination_stats/rq1_group_jaccard_distance_matrix.tsv
# results/rq1/ordination_stats/rq1_class_jaccard_distance_matrix.tsv
#
# Main outputs:
# results/rq1/within_between_similarity/
# ============================================================

# ------------------------------------------------------------
# 1. Required packages
# ------------------------------------------------------------

required_packages <- c(
  "ggplot2",
  "dplyr"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    FUN.VALUE = logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste0(
      "The following required R packages are missing:\n",
      paste(missing_packages, collapse = ", "),
      "\nInstall them before running this script."
    )
  )
}

library(ggplot2)
library(dplyr)

# ------------------------------------------------------------
# 2. User-adjustable settings
# ------------------------------------------------------------

input_dir <- file.path(
  "results",
  "rq1",
  "ordination_stats"
)

output_dir <- file.path(
  "results",
  "rq1",
  "within_between_similarity"
)

expected_number_of_cities <- 16

group_distance_file <- file.path(
  input_dir,
  "rq1_group_jaccard_distance_matrix.tsv"
)

class_distance_file <- file.path(
  input_dir,
  "rq1_class_jaccard_distance_matrix.tsv"
)

if (!dir.exists(output_dir)) {
  dir.create(
    output_dir,
    recursive = TRUE
  )
}

# ------------------------------------------------------------
# 3. Check required input files
# ------------------------------------------------------------

required_input_files <- c(
  group_distance_file,
  class_distance_file
)

missing_input_files <- required_input_files[
  !file.exists(required_input_files)
]

if (length(missing_input_files) > 0) {
  stop(
    paste0(
      "The following required input files are missing:\n",
      paste(missing_input_files, collapse = "\n")
    )
  )
}

# ------------------------------------------------------------
# 4. Helper function: read Jaccard distance matrix
# ------------------------------------------------------------

read_jaccard_distance_matrix <- function(file_path, level_name) {

  message(
    "\nReading ",
    level_name,
    " Jaccard distance matrix:\n",
    file_path
  )

  raw_df <- read.delim(
    file = file_path,
    header = TRUE,
    sep = "\t",
    check.names = FALSE,
    stringsAsFactors = FALSE,
    quote = "",
    comment.char = ""
  )

  if (ncol(raw_df) < 2) {
    stop(
      paste0(
        level_name,
        ": distance matrix must contain one profile column and at least one distance column."
      )
    )
  }

  profile_ids <- trimws(
    as.character(raw_df[[1]])
  )

  if (any(is.na(profile_ids)) || any(profile_ids == "")) {
    stop(
      paste0(
        level_name,
        ": missing or empty profile names detected in the first column."
      )
    )
  }

  value_df <- raw_df[
    ,
    -1,
    drop = FALSE
  ]

  value_df[] <- lapply(
    value_df,
    function(x) {
      suppressWarnings(
        as.numeric(x)
      )
    }
  )

  distance_matrix <- as.matrix(
    value_df
  )

  rownames(distance_matrix) <- profile_ids

  if (any(is.na(distance_matrix))) {
    stop(
      paste0(
        level_name,
        ": distance matrix contains missing or non-numeric values."
      )
    )
  }

  storage.mode(distance_matrix) <- "numeric"

  if (nrow(distance_matrix) != ncol(distance_matrix)) {
    stop(
      paste0(
        level_name,
        ": distance matrix is not square."
      )
    )
  }

  if (!setequal(rownames(distance_matrix), colnames(distance_matrix))) {
    stop(
      paste0(
        level_name,
        ": row and column profile names do not match."
      )
    )
  }

  distance_matrix <- distance_matrix[
    rownames(distance_matrix),
    rownames(distance_matrix),
    drop = FALSE
  ]

  if (max(abs(distance_matrix - t(distance_matrix))) > 1e-10) {
    stop(
      paste0(
        level_name,
        ": distance matrix is not symmetric."
      )
    )
  }

  if (max(abs(diag(distance_matrix))) > 1e-10) {
    stop(
      paste0(
        level_name,
        ": distance matrix diagonal is not zero."
      )
    )
  }

  if (any(distance_matrix < 0) || any(distance_matrix > 1)) {
    stop(
      paste0(
        level_name,
        ": Jaccard distance values should lie between 0 and 1."
      )
    )
  }

  message(
    level_name,
    ": ",
    nrow(distance_matrix),
    " profiles × ",
    ncol(distance_matrix),
    " profiles"
  )

  return(distance_matrix)
}

# ------------------------------------------------------------
# 5. Helper function: build metadata from profile names
# ------------------------------------------------------------

build_profile_metadata <- function(distance_matrix, level_name) {

  metadata <- data.frame(
    Profile = rownames(distance_matrix),
    stringsAsFactors = FALSE
  )

  metadata$Environment <- sub(
    "^.*_(Sewage|Transit)$",
    "\\1",
    metadata$Profile
  )

  metadata$City <- sub(
    "_(Sewage|Transit)$",
    "",
    metadata$Profile
  )

  if (!all(metadata$Environment %in% c("Sewage", "Transit"))) {
    stop(
      paste0(
        level_name,
        ": environment could not be extracted from some profile names:\n",
        paste(metadata$Profile, collapse = "\n")
      )
    )
  }

  metadata$Environment <- factor(
    metadata$Environment,
    levels = c(
      "Sewage",
      "Transit"
    )
  )

  rownames(metadata) <- metadata$Profile

  city_environment_table <- table(
    metadata$City,
    metadata$Environment
  )

  if (!all(city_environment_table == 1)) {
    print(
      city_environment_table
    )

    stop(
      paste0(
        level_name,
        ": each city must contain exactly one sewage and one transit profile."
      )
    )
  }

  if (length(unique(metadata$City)) != expected_number_of_cities) {
    warning(
      paste0(
        level_name,
        ": expected ",
        expected_number_of_cities,
        " matched cities, but found ",
        length(unique(metadata$City)),
        "."
      )
    )
  }

  metadata <- metadata[
    order(
      metadata$City,
      metadata$Environment
    ),
    ,
    drop = FALSE
  ]

  return(metadata)
}

# ------------------------------------------------------------
# 6. Helper function: generate sewage-transit pair data
# ------------------------------------------------------------

generate_within_between_pairs <- function(
  distance_matrix,
  metadata,
  level_name
) {

  distance_matrix <- distance_matrix[
    metadata$Profile,
    metadata$Profile,
    drop = FALSE
  ]

  sewage_profiles <- metadata$Profile[
    metadata$Environment == "Sewage"
  ]

  transit_profiles <- metadata$Profile[
    metadata$Environment == "Transit"
  ]

  comparison_df <- expand.grid(
    Sewage_profile = sewage_profiles,
    Transit_profile = transit_profiles,
    stringsAsFactors = FALSE
  )

  comparison_df$Sewage_city <- metadata[
    comparison_df$Sewage_profile,
    "City"
  ]

  comparison_df$Transit_city <- metadata[
    comparison_df$Transit_profile,
    "City"
  ]

  comparison_df$Jaccard_distance <- mapply(
    function(sewage_profile, transit_profile) {
      distance_matrix[
        sewage_profile,
        transit_profile
      ]
    },
    comparison_df$Sewage_profile,
    comparison_df$Transit_profile
  )

  comparison_df$Jaccard_similarity <- 1 -
    comparison_df$Jaccard_distance

  comparison_df$Comparison <- ifelse(
    comparison_df$Sewage_city == comparison_df$Transit_city,
    "Within-city\n(Sewage vs Transit)",
    "Between-city\n(Sewage vs Transit)"
  )

  comparison_df$Comparison <- factor(
    comparison_df$Comparison,
    levels = c(
      "Between-city\n(Sewage vs Transit)",
      "Within-city\n(Sewage vs Transit)"
    )
  )

  comparison_df$Level <- level_name

  expected_total_pairs <- expected_number_of_cities *
    expected_number_of_cities

  if (nrow(comparison_df) != expected_total_pairs) {
    warning(
      paste0(
        level_name,
        ": expected ",
        expected_total_pairs,
        " sewage-transit comparisons but found ",
        nrow(comparison_df),
        "."
      )
    )
  }

  expected_within_pairs <- expected_number_of_cities

  observed_within_pairs <- sum(
    comparison_df$Comparison == "Within-city\n(Sewage vs Transit)"
  )

  if (observed_within_pairs != expected_within_pairs) {
    warning(
      paste0(
        level_name,
        ": expected ",
        expected_within_pairs,
        " within-city comparisons but found ",
        observed_within_pairs,
        "."
      )
    )
  }

  return(comparison_df)
}

# ------------------------------------------------------------
# 7. Helper function: summarise pairwise similarities
# ------------------------------------------------------------

summarise_similarity <- function(comparison_df) {

  summary_stats <- comparison_df %>%
    group_by(
      Level,
      Comparison
    ) %>%
    summarise(
      n = n(),
      mean = mean(Jaccard_similarity),
      median = median(Jaccard_similarity),
      Q1 = quantile(
        Jaccard_similarity,
        0.25
      ),
      Q3 = quantile(
        Jaccard_similarity,
        0.75
      ),
      IQR = IQR(
        Jaccard_similarity
      ),
      min = min(
        Jaccard_similarity
      ),
      max = max(
        Jaccard_similarity
      ),
      .groups = "drop"
    )

  return(summary_stats)
}

# ------------------------------------------------------------
# 8. Helper function: publication-ready plot
# ------------------------------------------------------------

plot_within_between_similarity <- function(
  comparison_df,
  summary_stats,
  level_name
) {

  box_fill_colours <- c(
    "Between-city\n(Sewage vs Transit)" = "#F4A29A",
    "Within-city\n(Sewage vs Transit)" = "#8DB9E2"
  )

  box_line_colours <- c(
    "Between-city\n(Sewage vs Transit)" = "#E64B35",
    "Within-city\n(Sewage vs Transit)" = "#2166AC"
  )

  max_similarity <- max(
    comparison_df$Jaccard_similarity,
    na.rm = TRUE
  )

  y_axis_upper <- ceiling(
    (max_similarity + 0.08) * 10
  ) / 10

  y_axis_upper <- min(
    1,
    max(
      0.3,
      y_axis_upper
    )
  )

  y_break_interval <- ifelse(
    y_axis_upper <= 0.5,
    0.1,
    0.2
  )

  annotation_df <- summary_stats %>%
    mutate(
      label = paste0(
        "n = ",
        n
      ),
      y_position = y_axis_upper - 0.035
    )

  set.seed(123)

  p <- ggplot(
    comparison_df,
    aes(
      x = Comparison,
      y = Jaccard_similarity,
      fill = Comparison,
      colour = Comparison
    )
  ) +

    geom_boxplot(
      width = 0.52,
      alpha = 0.55,
      linewidth = 1.05,
      outlier.shape = NA
    ) +

    geom_jitter(
      width = 0.105,
      height = 0,
      size = 1.15,
      alpha = 0.34,
      shape = 16,
      stroke = 0
    ) +

    geom_text(
      data = annotation_df,
      aes(
        x = Comparison,
        y = y_position,
        label = label
      ),
      inherit.aes = FALSE,
      size = 5.1,
      colour = "black"
    ) +

    scale_fill_manual(
      values = box_fill_colours,
      guide = "none"
    ) +

    scale_colour_manual(
      values = box_line_colours,
      guide = "none"
    ) +

    scale_y_continuous(
      limits = c(
        0,
        y_axis_upper
      ),
      breaks = seq(
        0,
        y_axis_upper,
        by = y_break_interval
      ),
      labels = function(x) {
        sprintf(
          "%.1f",
          x
        )
      },
      expand = expansion(
        mult = c(
          0,
          0.01
        )
      )
    ) +

    labs(
      x = NULL,
      y = "Jaccard similarity"
    ) +

    theme_minimal(
      base_size = 18
    ) +

    theme(
      panel.grid.major.x = element_blank(),

      panel.grid.major.y = element_line(
        colour = "grey86",
        linewidth = 0.75
      ),

      panel.grid.minor = element_blank(),

      panel.border = element_rect(
        colour = "black",
        fill = NA,
        linewidth = 1.05
      ),

      axis.title.y = element_text(
        size = 19,
        colour = "black",
        margin = margin(
          r = 12
        )
      ),

      axis.text.y = element_text(
        size = 16,
        colour = "black"
      ),

      axis.text.x = element_text(
        size = 17,
        colour = "black",
        lineheight = 1.08,
        margin = margin(
          t = 10
        )
      ),

      axis.ticks.y = element_line(
        colour = "black",
        linewidth = 0.55
      ),

      axis.ticks.x = element_blank(),

      panel.background = element_rect(
        fill = "white",
        colour = NA
      ),

      plot.background = element_rect(
        fill = "white",
        colour = NA
      ),

      plot.margin = margin(
        t = 16,
        r = 18,
        b = 16,
        l = 18
      )
    )

  return(p)
}

# ------------------------------------------------------------
# 9. Main function
# ------------------------------------------------------------

run_within_between_analysis <- function(
  distance_file,
  level_name,
  output_prefix
) {

  message(
    "\n============================================================"
  )

  message(
    "Running within-city vs between-city similarity analysis: ",
    level_name
  )

  message(
    "============================================================"
  )

  distance_matrix <- read_jaccard_distance_matrix(
    file_path = distance_file,
    level_name = level_name
  )

  metadata <- build_profile_metadata(
    distance_matrix = distance_matrix,
    level_name = level_name
  )

  distance_matrix <- distance_matrix[
    metadata$Profile,
    metadata$Profile,
    drop = FALSE
  ]

  comparison_df <- generate_within_between_pairs(
    distance_matrix = distance_matrix,
    metadata = metadata,
    level_name = level_name
  )

  summary_stats <- summarise_similarity(
    comparison_df = comparison_df
  )

  message(
    "\nSummary statistics for ",
    level_name,
    ":"
  )

  print(
    summary_stats
  )

  p <- plot_within_between_similarity(
    comparison_df = comparison_df,
    summary_stats = summary_stats,
    level_name = level_name
  )

  plot_data_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_within_between_city_similarity_plotdata.tsv"
    )
  )

  summary_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_within_between_city_similarity_summary.tsv"
    )
  )

  png_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_within_between_city_jaccard_similarity.png"
    )
  )

  pdf_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_within_between_city_jaccard_similarity.pdf"
    )
  )

  write.table(
    comparison_df,
    file = plot_data_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    summary_stats,
    file = summary_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  ggsave(
    filename = png_output,
    plot = p,
    width = 10.8,
    height = 7.6,
    units = "in",
    dpi = 600,
    bg = "white"
  )

  ggsave(
    filename = pdf_output,
    plot = p,
    width = 10.8,
    height = 7.6,
    units = "in",
    bg = "white"
  )

  message(
    "\nFiles written for ",
    level_name,
    ":"
  )

  message(plot_data_output)
  message(summary_output)
  message(png_output)
  message(pdf_output)

  return(
    list(
      comparison_data = comparison_df,
      summary = summary_stats,
      plot = p
    )
  )
}

# ------------------------------------------------------------
# 10. Run ARG Group analysis
# ------------------------------------------------------------

group_results <- run_within_between_analysis(
  distance_file = group_distance_file,
  level_name = "ARG Group",
  output_prefix = "rq1_group"
)

# ------------------------------------------------------------
# 11. Run Resistance Class analysis
# ------------------------------------------------------------

class_results <- run_within_between_analysis(
  distance_file = class_distance_file,
  level_name = "Resistance Class",
  output_prefix = "rq1_class"
)

# ------------------------------------------------------------
# 12. Save combined outputs
# ------------------------------------------------------------

combined_plot_data <- rbind(
  group_results$comparison_data,
  class_results$comparison_data
)

combined_summary <- rbind(
  group_results$summary,
  class_results$summary
)

combined_plot_data_output <- file.path(
  output_dir,
  "rq1_combined_within_between_city_similarity_plotdata.tsv"
)

combined_summary_output <- file.path(
  output_dir,
  "rq1_combined_within_between_city_similarity_summary.tsv"
)

write.table(
  combined_plot_data,
  file = combined_plot_data_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  combined_summary,
  file = combined_summary_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

message(
  "\n============================================================"
)

message(
  "RQ1 within-city vs between-city similarity analysis completed."
)

message(
  "Combined outputs:"
)

message(combined_plot_data_output)
message(combined_summary_output)

message(
  "============================================================"
)
