# ============================================================
# 05_rq1_negative_eigenvalue_audit.R
#
# Purpose:
# Audit negative eigenvalues in RQ1 Jaccard-based PCoA and
# generate Lingoes-corrected PCoA coordinates where needed.
#
# Background:
# Jaccard distances can produce negative eigenvalues in PCoA.
# This script checks whether negative eigenvalues are meaningful
# and applies Lingoes correction for corrected visualisation when
# required.
#
# Input:
# Jaccard distance matrices generated by:
# 03_rq1_jaccard_pcoa_permanova.R
#
# Expected input files:
# results/rq1/ordination_stats/rq1_group_jaccard_distance_matrix.tsv
# results/rq1/ordination_stats/rq1_class_jaccard_distance_matrix.tsv
#
# Main outputs:
# results/rq1/eigenvalue_audit/
# ============================================================

# ------------------------------------------------------------
# 1. Required packages
# ------------------------------------------------------------

required_packages <- c(
  "ape"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    FUN.VALUE = logical(1),
    quietly = TRUE
  )
]

if (length(missing_packages) > 0) {
  stop(
    paste0(
      "The following required R packages are missing:\n",
      paste(missing_packages, collapse = ", "),
      "\nInstall them before running this script."
    )
  )
}

library(ape)

# ------------------------------------------------------------
# 2. User-adjustable settings
# ------------------------------------------------------------

input_dir <- file.path(
  "results",
  "rq1",
  "ordination_stats"
)

output_dir <- file.path(
  "results",
  "rq1",
  "eigenvalue_audit"
)

expected_number_of_cities <- 16

# A negative inertia ratio above this value is treated as
# meaningful enough to report and correct for visualisation.
meaningful_negative_inertia_threshold <- 0.01

group_distance_file <- file.path(
  input_dir,
  "rq1_group_jaccard_distance_matrix.tsv"
)

class_distance_file <- file.path(
  input_dir,
  "rq1_class_jaccard_distance_matrix.tsv"
)

if (!dir.exists(output_dir)) {
  dir.create(
    output_dir,
    recursive = TRUE
  )
}

# ------------------------------------------------------------
# 3. Check required input files
# ------------------------------------------------------------

required_input_files <- c(
  group_distance_file,
  class_distance_file
)

missing_input_files <- required_input_files[
  !file.exists(required_input_files)
]

if (length(missing_input_files) > 0) {
  stop(
    paste0(
      "The following required input files are missing:\n",
      paste(missing_input_files, collapse = "\n")
    )
  )
}

# ------------------------------------------------------------
# 4. Helper function: read Jaccard distance matrix
# ------------------------------------------------------------

read_jaccard_distance_matrix <- function(file_path, level_name) {

  message(
    "\nReading ",
    level_name,
    " Jaccard distance matrix:\n",
    file_path
  )

  raw_df <- read.delim(
    file = file_path,
    header = TRUE,
    sep = "\t",
    check.names = FALSE,
    stringsAsFactors = FALSE,
    quote = "",
    comment.char = ""
  )

  if (ncol(raw_df) < 2) {
    stop(
      paste0(
        level_name,
        ": distance matrix must contain one profile column and at least one distance column."
      )
    )
  }

  profile_ids <- trimws(
    as.character(raw_df[[1]])
  )

  if (any(is.na(profile_ids)) || any(profile_ids == "")) {
    stop(
      paste0(
        level_name,
        ": missing or empty profile names detected in the first column."
      )
    )
  }

  value_df <- raw_df[
    ,
    -1,
    drop = FALSE
  ]

  value_df[] <- lapply(
    value_df,
    function(x) {
      suppressWarnings(
        as.numeric(x)
      )
    }
  )

  distance_matrix <- as.matrix(
    value_df
  )

  rownames(distance_matrix) <- profile_ids

  if (any(is.na(distance_matrix))) {
    stop(
      paste0(
        level_name,
        ": distance matrix contains missing or non-numeric values."
      )
    )
  }

  storage.mode(distance_matrix) <- "numeric"

  if (nrow(distance_matrix) != ncol(distance_matrix)) {
    stop(
      paste0(
        level_name,
        ": distance matrix is not square."
      )
    )
  }

  if (!setequal(rownames(distance_matrix), colnames(distance_matrix))) {
    stop(
      paste0(
        level_name,
        ": row and column profile names do not match."
      )
    )
  }

  distance_matrix <- distance_matrix[
    rownames(distance_matrix),
    rownames(distance_matrix),
    drop = FALSE
  ]

  if (max(abs(distance_matrix - t(distance_matrix))) > 1e-10) {
    stop(
      paste0(
        level_name,
        ": distance matrix is not symmetric."
      )
    )
  }

  if (max(abs(diag(distance_matrix))) > 1e-10) {
    stop(
      paste0(
        level_name,
        ": distance matrix diagonal is not zero."
      )
    )
  }

  if (any(distance_matrix < 0) || any(distance_matrix > 1)) {
    stop(
      paste0(
        level_name,
        ": Jaccard distance values should lie between 0 and 1."
      )
    )
  }

  message(
    level_name,
    ": ",
    nrow(distance_matrix),
    " profiles × ",
    ncol(distance_matrix),
    " profiles"
  )

  return(distance_matrix)
}

# ------------------------------------------------------------
# 5. Helper function: build profile metadata
# ------------------------------------------------------------

build_profile_metadata <- function(distance_matrix, level_name) {

  metadata <- data.frame(
    Profile = rownames(distance_matrix),
    stringsAsFactors = FALSE
  )

  metadata$Environment <- sub(
    "^.*_(Sewage|Transit)$",
    "\\1",
    metadata$Profile
  )

  metadata$City <- sub(
    "_(Sewage|Transit)$",
    "",
    metadata$Profile
  )

  if (!all(metadata$Environment %in% c("Sewage", "Transit"))) {
    stop(
      paste0(
        level_name,
        ": environment could not be extracted from some profile names:\n",
        paste(metadata$Profile, collapse = "\n")
      )
    )
  }

  metadata$Environment <- factor(
    metadata$Environment,
    levels = c(
      "Sewage",
      "Transit"
    )
  )

  rownames(metadata) <- metadata$Profile

  city_environment_table <- table(
    metadata$City,
    metadata$Environment
  )

  if (!all(city_environment_table == 1)) {
    print(
      city_environment_table
    )

    stop(
      paste0(
        level_name,
        ": each city must contain exactly one sewage and one transit profile."
      )
    )
  }

  if (length(unique(metadata$City)) != expected_number_of_cities) {
    warning(
      paste0(
        level_name,
        ": expected ",
        expected_number_of_cities,
        " matched cities, but found ",
        length(unique(metadata$City)),
        "."
      )
    )
  }

  metadata <- metadata[
    order(
      metadata$City,
      metadata$Environment
    ),
    ,
    drop = FALSE
  ]

  return(metadata)
}

# ------------------------------------------------------------
# 6. Helper function: calculate uncorrected eigenvalue summary
# ------------------------------------------------------------

calculate_uncorrected_eigen_summary <- function(
  distance_matrix,
  level_name
) {

  distance_object <- as.dist(
    distance_matrix
  )

  pcoa_uncorrected <- stats::cmdscale(
    distance_object,
    k = 2,
    eig = TRUE
  )

  eigenvalues <- pcoa_uncorrected$eig

  positive_eigenvalues <- eigenvalues[
    eigenvalues > 0
  ]

  negative_eigenvalues <- eigenvalues[
    eigenvalues < 0
  ]

  sum_positive <- sum(
    positive_eigenvalues
  )

  sum_absolute_negative <- sum(
    abs(
      negative_eigenvalues
    )
  )

  negative_inertia_ratio <- ifelse(
    sum_positive > 0,
    sum_absolute_negative / sum_positive,
    NA
  )

  pcoa1_percent <- 100 *
    eigenvalues[1] /
    sum_positive

  pcoa2_percent <- 100 *
    eigenvalues[2] /
    sum_positive

  correction_recommended <- isTRUE(
    negative_inertia_ratio > meaningful_negative_inertia_threshold
  )

  eigenvalue_table <- data.frame(
    Level = level_name,
    Axis = seq_along(
      eigenvalues
    ),
    Eigenvalue = eigenvalues,
    Positive = eigenvalues > 0,
    Negative = eigenvalues < 0,
    stringsAsFactors = FALSE
  )

  summary_table <- data.frame(
    Level = level_name,
    Method = "Uncorrected cmdscale PCoA",
    Number_of_profiles = nrow(distance_matrix),
    Number_of_positive_eigenvalues = sum(eigenvalues > 0),
    Number_of_negative_eigenvalues = sum(eigenvalues < 0),
    Sum_positive_eigenvalues = sum_positive,
    Sum_absolute_negative_eigenvalues = sum_absolute_negative,
    Most_negative_eigenvalue = ifelse(
      length(negative_eigenvalues) > 0,
      min(negative_eigenvalues),
      0
    ),
    Negative_inertia_relative_to_positive_inertia = negative_inertia_ratio,
    Meaningful_negative_inertia_threshold = meaningful_negative_inertia_threshold,
    Correction_recommended_for_visualisation = correction_recommended,
    PCoA1_percent_positive_inertia = pcoa1_percent,
    PCoA2_percent_positive_inertia = pcoa2_percent,
    stringsAsFactors = FALSE
  )

  return(
    list(
      cmdscale_result = pcoa_uncorrected,
      eigenvalue_table = eigenvalue_table,
      summary_table = summary_table
    )
  )
}

# ------------------------------------------------------------
# 7. Helper function: Lingoes-corrected PCoA
# ------------------------------------------------------------

calculate_lingoes_pcoa <- function(
  distance_matrix,
  metadata,
  level_name
) {

  distance_object <- as.dist(
    distance_matrix
  )

  lingoes_result <- ape::pcoa(
    distance_object,
    correction = "lingoes"
  )

  if (!"vectors.cor" %in% names(lingoes_result)) {
    stop(
      paste0(
        level_name,
        ": Lingoes-corrected coordinates were not returned by ape::pcoa()."
      )
    )
  }

  corrected_coordinates <- lingoes_result$vectors.cor[
    ,
    1:2,
    drop = FALSE
  ]

  corrected_eigenvalues <- lingoes_result$values$Corr_eig

  positive_corrected_eigenvalues <- corrected_eigenvalues[
    corrected_eigenvalues > 0
  ]

  corrected_pcoa1_percent <- 100 *
    corrected_eigenvalues[1] /
    sum(positive_corrected_eigenvalues)

  corrected_pcoa2_percent <- 100 *
    corrected_eigenvalues[2] /
    sum(positive_corrected_eigenvalues)

  coordinate_df <- data.frame(
    Profile = rownames(corrected_coordinates),
    City = metadata[
      rownames(corrected_coordinates),
      "City"
    ],
    Environment = metadata[
      rownames(corrected_coordinates),
      "Environment"
    ],
    PCoA1 = corrected_coordinates[
      ,
      1
    ],
    PCoA2 = corrected_coordinates[
      ,
      2
    ],
    stringsAsFactors = FALSE
  )

  eigenvalue_df <- data.frame(
    Level = level_name,
    Axis = seq_along(
      corrected_eigenvalues
    ),
    Corrected_eigenvalue = corrected_eigenvalues,
    Positive = corrected_eigenvalues > 0,
    stringsAsFactors = FALSE
  )

  summary_df <- data.frame(
    Level = level_name,
    Method = "Lingoes-corrected PCoA",
    Correction = "lingoes",
    Correction_constant = lingoes_result$values$correction,
    Number_of_corrected_positive_eigenvalues = sum(
      corrected_eigenvalues > 0
    ),
    PCoA1_percent_corrected_positive_inertia = corrected_pcoa1_percent,
    PCoA2_percent_corrected_positive_inertia = corrected_pcoa2_percent,
    stringsAsFactors = FALSE
  )

  return(
    list(
      lingoes_result = lingoes_result,
      coordinates = coordinate_df,
      eigenvalues = eigenvalue_df,
      summary = summary_df
    )
  )
}

# ------------------------------------------------------------
# 8. Main function: eigenvalue audit
# ------------------------------------------------------------

run_negative_eigenvalue_audit <- function(
  distance_file,
  level_name,
  output_prefix
) {

  message(
    "\n============================================================"
  )

  message(
    "Running negative eigenvalue audit: ",
    level_name
  )

  message(
    "============================================================"
  )

  distance_matrix <- read_jaccard_distance_matrix(
    file_path = distance_file,
    level_name = level_name
  )

  metadata <- build_profile_metadata(
    distance_matrix = distance_matrix,
    level_name = level_name
  )

  distance_matrix <- distance_matrix[
    metadata$Profile,
    metadata$Profile,
    drop = FALSE
  ]

  # ----------------------------------------------------------
  # 8.1 Uncorrected eigenvalue audit
  # ----------------------------------------------------------

  uncorrected <- calculate_uncorrected_eigen_summary(
    distance_matrix = distance_matrix,
    level_name = level_name
  )

  uncorrected_coordinates <- data.frame(
    Profile = rownames(distance_matrix),
    City = metadata$City,
    Environment = metadata$Environment,
    PCoA1 = uncorrected$cmdscale_result$points[
      ,
      1
    ],
    PCoA2 = uncorrected$cmdscale_result$points[
      ,
      2
    ],
    stringsAsFactors = FALSE
  )

  # ----------------------------------------------------------
  # 8.2 Lingoes correction
  #
  # A corrected PCoA is generated for every level so that
  # coordinates are available for comparison. In interpretation,
  # correction is required only when negative inertia is meaningful.
  # ----------------------------------------------------------

  lingoes <- calculate_lingoes_pcoa(
    distance_matrix = distance_matrix,
    metadata = metadata,
    level_name = level_name
  )

  # ----------------------------------------------------------
  # 8.3 Compare uncorrected and corrected configurations
  #
  # This checks whether Lingoes correction materially changes the
  # two-dimensional ordination structure.
  # ----------------------------------------------------------

  common_profiles <- intersect(
    uncorrected_coordinates$Profile,
    lingoes$coordinates$Profile
  )

  uncorrected_xy <- as.matrix(
    uncorrected_coordinates[
      match(
        common_profiles,
        uncorrected_coordinates$Profile
      ),
      c(
        "PCoA1",
        "PCoA2"
      )
    ]
  )

  corrected_xy <- as.matrix(
    lingoes$coordinates[
      match(
        common_profiles,
        lingoes$coordinates$Profile
      ),
      c(
        "PCoA1",
        "PCoA2"
      )
    ]
  )

  uncorrected_pairwise <- stats::dist(
    uncorrected_xy
  )

  corrected_pairwise <- stats::dist(
    corrected_xy
  )

  interpoint_distance_correlation <- stats::cor(
    as.vector(uncorrected_pairwise),
    as.vector(corrected_pairwise),
    method = "pearson"
  )

  correction_comparison <- data.frame(
    Level = level_name,
    Number_of_profiles = length(common_profiles),
    Interpoint_distance_correlation_uncorrected_vs_lingoes =
      interpoint_distance_correlation,
    stringsAsFactors = FALSE
  )

  # ----------------------------------------------------------
  # 8.4 Write outputs
  # ----------------------------------------------------------

  uncorrected_eigenvalues_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_uncorrected_pcoa_eigenvalues.tsv"
    )
  )

  uncorrected_summary_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_negative_eigenvalue_audit_summary.tsv"
    )
  )

  uncorrected_coordinates_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_uncorrected_pcoa_coordinates.tsv"
    )
  )

  lingoes_coordinates_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_lingoes_pcoa_coordinates.tsv"
    )
  )

  lingoes_eigenvalues_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_lingoes_pcoa_eigenvalues.tsv"
    )
  )

  lingoes_summary_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_lingoes_pcoa_summary.tsv"
    )
  )

  correction_comparison_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_uncorrected_vs_lingoes_comparison.tsv"
    )
  )

  metadata_output <- file.path(
    output_dir,
    paste0(
      output_prefix,
      "_eigenvalue_audit_metadata.tsv"
    )
  )

  write.table(
    uncorrected$eigenvalue_table,
    file = uncorrected_eigenvalues_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    uncorrected$summary_table,
    file = uncorrected_summary_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    uncorrected_coordinates,
    file = uncorrected_coordinates_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    lingoes$coordinates,
    file = lingoes_coordinates_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    lingoes$eigenvalues,
    file = lingoes_eigenvalues_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    lingoes$summary,
    file = lingoes_summary_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    correction_comparison,
    file = correction_comparison_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  write.table(
    metadata,
    file = metadata_output,
    sep = "\t",
    quote = FALSE,
    row.names = FALSE
  )

  message(
    "\nNegative eigenvalue audit summary for ",
    level_name,
    ":"
  )

  print(
    uncorrected$summary_table
  )

  message(
    "\nLingoes-corrected PCoA summary for ",
    level_name,
    ":"
  )

  print(
    lingoes$summary
  )

  message(
    "\nUncorrected vs Lingoes comparison for ",
    level_name,
    ":"
  )

  print(
    correction_comparison
  )

  message(
    "\nFiles written for ",
    level_name,
    ":"
  )

  message(uncorrected_eigenvalues_output)
  message(uncorrected_summary_output)
  message(uncorrected_coordinates_output)
  message(lingoes_coordinates_output)
  message(lingoes_eigenvalues_output)
  message(lingoes_summary_output)
  message(correction_comparison_output)
  message(metadata_output)

  return(
    list(
      uncorrected_summary = uncorrected$summary_table,
      lingoes_summary = lingoes$summary,
      correction_comparison = correction_comparison
    )
  )
}

# ------------------------------------------------------------
# 9. Run ARG Group audit
# ------------------------------------------------------------

group_results <- run_negative_eigenvalue_audit(
  distance_file = group_distance_file,
  level_name = "ARG Group",
  output_prefix = "rq1_group"
)

# ------------------------------------------------------------
# 10. Run Resistance Class audit
# ------------------------------------------------------------

class_results <- run_negative_eigenvalue_audit(
  distance_file = class_distance_file,
  level_name = "Resistance Class",
  output_prefix = "rq1_class"
)

# ------------------------------------------------------------
# 11. Save combined summaries
# ------------------------------------------------------------

combined_negative_eigenvalue_summary <- rbind(
  group_results$uncorrected_summary,
  class_results$uncorrected_summary
)

combined_lingoes_summary <- rbind(
  group_results$lingoes_summary,
  class_results$lingoes_summary
)

combined_correction_comparison <- rbind(
  group_results$correction_comparison,
  class_results$correction_comparison
)

combined_negative_eigenvalue_output <- file.path(
  output_dir,
  "rq1_combined_negative_eigenvalue_audit_summary.tsv"
)

combined_lingoes_output <- file.path(
  output_dir,
  "rq1_combined_lingoes_pcoa_summary.tsv"
)

combined_correction_comparison_output <- file.path(
  output_dir,
  "rq1_combined_uncorrected_vs_lingoes_comparison.tsv"
)

write.table(
  combined_negative_eigenvalue_summary,
  file = combined_negative_eigenvalue_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  combined_lingoes_summary,
  file = combined_lingoes_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

write.table(
  combined_correction_comparison,
  file = combined_correction_comparison_output,
  sep = "\t",
  quote = FALSE,
  row.names = FALSE
)

message(
  "\n============================================================"
)

message(
  "RQ1 negative eigenvalue audit completed."
)

message(
  "Combined outputs:"
)

message(combined_negative_eigenvalue_output)
message(combined_lingoes_output)
message(combined_correction_comparison_output)

message(
  "============================================================"
)
