#!/usr/bin/env bash

# 01_profile_sewage_resistome_analyzer_megares.sh
#
# Purpose:
# Profile antimicrobial resistance features from sewage SAM files using
# ResistomeAnalyzer with MEGARes v3.00 annotations.
#
# Workflow:
# 1. Read SAM files generated by Bowtie2 mapping against MEGARes v3.00.
# 2. Run ResistomeAnalyzer with an 80% gene-fraction threshold.
# 3. Generate output tables at gene, group, mechanism, and class levels.
#
# Expected input structure:
#   <sam-dir>/<City>/<City>_vs_MEGARes_v3.sam
#
# Output structure:
#   <output-dir>/<City>/<City>_gene.tsv
#   <output-dir>/<City>/<City>_group.tsv
#   <output-dir>/<City>/<City>_mechanism.tsv
#   <output-dir>/<City>/<City>_class.tsv
#
# Example run:
#   bash scripts/08_arg_profiling/01_profile_sewage_resistome_analyzer_megares.sh \
#     --sam-dir results/amr_mapping/sewage/megares_v3/sam \
#     --megares-fasta database/megares_v3/megares_database_v3.00.fasta \
#     --megares-annotations database/megares_v3/megares_annotations_v3.00.csv \
#     --resistome-bin resistome \
#     --output-dir results/amr_tables/sewage/megares_v3/resistome_analyzer \
#     --logdir logs/08_arg_profiling_sewage \
#     --threshold 80

set -euo pipefail

SAM_DIR="results/amr_mapping/sewage/megares_v3/sam"
MEGARES_FASTA=""
MEGARES_ANNOTATIONS=""
RESISTOME_BIN="resistome"
OUTPUT_DIR="results/amr_tables/sewage/megares_v3/resistome_analyzer"
LOGDIR="logs/08_arg_profiling_sewage"
THRESHOLD=80

usage() {
    echo ""
    echo "Usage:"
    echo "  bash scripts/08_arg_profiling/01_profile_sewage_resistome_analyzer_megares.sh \\"
    echo "    --sam-dir <sam_input_dir> \\"
    echo "    --megares-fasta <megares_reference_fasta> \\"
    echo "    --megares-annotations <megares_annotation_csv> \\"
    echo "    --resistome-bin <path_to_resistome_binary> \\"
    echo "    --output-dir <resistome_analyzer_output_dir> \\"
    echo "    --logdir <log_output_dir> \\"
    echo "    --threshold 80"
    echo ""
    echo "Required:"
    echo "  --megares-fasta        MEGARes v3.00 FASTA reference file"
    echo "  --megares-annotations  MEGARes v3.00 annotation CSV file"
    echo ""
    echo "Optional:"
    echo "  --sam-dir              Directory containing city-level SAM files"
    echo "                         Default: results/amr_mapping/sewage/megares_v3/sam"
    echo "  --resistome-bin        ResistomeAnalyzer executable or path to executable"
    echo "                         Default: resistome"
    echo "  --output-dir           Output directory for ResistomeAnalyzer TSV tables"
    echo "                         Default: results/amr_tables/sewage/megares_v3/resistome_analyzer"
    echo "  --logdir               Log directory"
    echo "                         Default: logs/08_arg_profiling_sewage"
    echo "  --threshold            Gene-fraction threshold"
    echo "                         Default: 80"
    echo ""
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --sam-dir)
            SAM_DIR="$2"
            shift 2
            ;;
        --megares-fasta)
            MEGARES_FASTA="$2"
            shift 2
            ;;
        --megares-annotations)
            MEGARES_ANNOTATIONS="$2"
            shift 2
            ;;
        --resistome-bin)
            RESISTOME_BIN="$2"
            shift 2
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --logdir)
            LOGDIR="$2"
            shift 2
            ;;
        --threshold)
            THRESHOLD="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "ERROR: Unknown argument: $1"
            usage
            exit 1
            ;;
    esac
done

if [[ ! -d "$SAM_DIR" ]]; then
    echo "ERROR: SAM input directory not found: $SAM_DIR"
    exit 1
fi

if [[ -z "$MEGARES_FASTA" ]]; then
    echo "ERROR: --megares-fasta is required."
    usage
    exit 1
fi

if [[ ! -f "$MEGARES_FASTA" ]]; then
    echo "ERROR: MEGARes FASTA file not found: $MEGARES_FASTA"
    exit 1
fi

if [[ -z "$MEGARES_ANNOTATIONS" ]]; then
    echo "ERROR: --megares-annotations is required."
    usage
    exit 1
fi

if [[ ! -f "$MEGARES_ANNOTATIONS" ]]; then
    echo "ERROR: MEGARes annotation CSV file not found: $MEGARES_ANNOTATIONS"
    exit 1
fi

if ! command -v "$RESISTOME_BIN" >/dev/null 2>&1; then
    if [[ ! -x "$RESISTOME_BIN" ]]; then
        echo "ERROR: ResistomeAnalyzer executable not found or not executable:"
        echo "$RESISTOME_BIN"
        echo ""
        echo "Use --resistome-bin to provide the executable path, for example:"
        echo "  --resistome-bin tools/resistomeanalyzer/resistome"
        exit 1
    fi
fi

mkdir -p "$OUTPUT_DIR"
mkdir -p "$LOGDIR"

VERSION_FILE="${LOGDIR}/software_versions_resistome_analyzer.txt"
MANIFEST="${LOGDIR}/sewage_resistome_analyzer_manifest.tsv"
FAILED="${LOGDIR}/failed_resistome_analyzer.tsv"

{
    echo "ResistomeAnalyzer profiling script run date: $(date)"
    echo ""
    echo "ResistomeAnalyzer executable:"
    echo "$RESISTOME_BIN"
    echo ""
    echo "ResistomeAnalyzer version/help output:"
    "$RESISTOME_BIN" 2>&1 | head -n 20 || true
    echo ""
    echo "MEGARes FASTA:"
    echo "$MEGARES_FASTA"
    echo ""
    echo "MEGARes annotations:"
    echo "$MEGARES_ANNOTATIONS"
    echo ""
    echo "Gene fraction threshold:"
    echo "$THRESHOLD"
} > "$VERSION_FILE"

echo -e "city\tsam_file\tgene_tsv\tgroup_tsv\tmechanism_tsv\tclass_tsv\tthreshold\tlog_file\tstatus" > "$MANIFEST"
echo -e "city\treason" > "$FAILED"

sanitize_name() {
    echo "$1" | sed 's/[^A-Za-z0-9._-]/_/g'
}

find_city_sam() {
    local city_dir="$1"
    local city_name="$2"

    local sam_file=""

    sam_file=$(find "$city_dir" -maxdepth 1 -type f \( \
        -name "${city_name}_vs_MEGARes_v3.sam" -o \
        -name "*_vs_MEGARes_v3.sam" -o \
        -name "*.sam" \
    \) | sort | head -n 1)

    echo "$sam_file"
}

echo ""
echo "Starting sewage ARG profiling using ResistomeAnalyzer"
echo "SAM input directory: $SAM_DIR"
echo "MEGARes FASTA: $MEGARES_FASTA"
echo "MEGARes annotations: $MEGARES_ANNOTATIONS"
echo "ResistomeAnalyzer executable: $RESISTOME_BIN"
echo "Output directory: $OUTPUT_DIR"
echo "Log directory: $LOGDIR"
echo "Gene fraction threshold: $THRESHOLD"
echo ""

while IFS= read -r CITY_DIR; do

    CITY=$(basename "$CITY_DIR")
    CITY_SAFE=$(sanitize_name "$CITY")

    echo "------------------------------------------------------------"
    echo "City: $CITY"
    echo "Input directory: $CITY_DIR"

    SAM_FILE=$(find_city_sam "$CITY_DIR" "$CITY")

    if [[ -z "$SAM_FILE" ]]; then
        echo "WARNING: Could not find SAM file for city: $CITY"
        echo -e "${CITY}\tsam_file_not_found" >> "$FAILED"
        continue
    fi

    if [[ ! -s "$SAM_FILE" ]]; then
        echo "WARNING: SAM file is empty for city: $CITY"
        echo -e "${CITY}\tsam_file_empty" >> "$FAILED"
        continue
    fi

    CITY_OUTPUT_DIR="${OUTPUT_DIR}/${CITY_SAFE}"
    mkdir -p "$CITY_OUTPUT_DIR"

    GENE_TSV="${CITY_OUTPUT_DIR}/${CITY_SAFE}_gene.tsv"
    GROUP_TSV="${CITY_OUTPUT_DIR}/${CITY_SAFE}_group.tsv"
    MECH_TSV="${CITY_OUTPUT_DIR}/${CITY_SAFE}_mechanism.tsv"
    CLASS_TSV="${CITY_OUTPUT_DIR}/${CITY_SAFE}_class.tsv"
    RUN_LOG="${LOGDIR}/${CITY_SAFE}_resistome_analyzer.log"

    echo "SAM file: $SAM_FILE"
    echo "Gene output: $GENE_TSV"
    echo "Group output: $GROUP_TSV"
    echo "Mechanism output: $MECH_TSV"
    echo "Class output: $CLASS_TSV"

    set +e
    "$RESISTOME_BIN" \
        -ref_fp "$MEGARES_FASTA" \
        -sam_fp "$SAM_FILE" \
        -annot_fp "$MEGARES_ANNOTATIONS" \
        -gene_fp "$GENE_TSV" \
        -group_fp "$GROUP_TSV" \
        -class_fp "$CLASS_TSV" \
        -mech_fp "$MECH_TSV" \
        -t "$THRESHOLD" \
        > "$RUN_LOG" 2>&1

    EXIT_CODE=$?
    set -e

    if [[ "$EXIT_CODE" -ne 0 ]]; then
        echo "WARNING: ResistomeAnalyzer failed for city: $CITY"
        echo "Check log: $RUN_LOG"
        echo -e "${CITY}\tresistome_analyzer_failed_exit_code_${EXIT_CODE}" >> "$FAILED"
        echo -e "${CITY}\t${SAM_FILE}\t${GENE_TSV}\t${GROUP_TSV}\t${MECH_TSV}\t${CLASS_TSV}\t${THRESHOLD}\t${RUN_LOG}\tfailed" >> "$MANIFEST"
        continue
    fi

    if [[ ! -s "$GENE_TSV" || ! -s "$GROUP_TSV" || ! -s "$MECH_TSV" || ! -s "$CLASS_TSV" ]]; then
        echo "WARNING: One or more output TSV files are missing or empty for city: $CITY"
        echo -e "${CITY}\tmissing_or_empty_output_tsv" >> "$FAILED"
        echo -e "${CITY}\t${SAM_FILE}\t${GENE_TSV}\t${GROUP_TSV}\t${MECH_TSV}\t${CLASS_TSV}\t${THRESHOLD}\t${RUN_LOG}\tfailed_missing_output" >> "$MANIFEST"
        continue
    fi

    echo -e "${CITY}\t${SAM_FILE}\t${GENE_TSV}\t${GROUP_TSV}\t${MECH_TSV}\t${CLASS_TSV}\t${THRESHOLD}\t${RUN_LOG}\tcompleted" >> "$MANIFEST"

done < <(find "$SAM_DIR" -mindepth 1 -maxdepth 1 -type d | sort)

echo ""
echo "Sewage ARG profiling complete."
echo "ResistomeAnalyzer output tables: $OUTPUT_DIR"
echo "Manifest: $MANIFEST"
echo "Failed profiling file: $FAILED"
echo "Software versions/help output: $VERSION_FILE"
echo ""
