#!/usr/bin/env bash

set -euo pipefail

# ============================================================
# Script: 06_transit_resistomeanalyzer_geneFrac80.sh
#
# Purpose:
#   Profile antimicrobial resistance genes from MEGARes-aligned
#   transit SAM files using the AMR++ / ResistomeAnalyzer framework.
#
# Workflow:
#   1. Read city-wise SAM files generated by Bowtie2 mapping
#   2. Run ResistomeAnalyzer using MEGARes v3.00 reference and annotation files
#   3. Apply an 80% gene-fraction threshold
#   4. Generate ARG profiles at four levels:
#      - gene
#      - group
#      - mechanism
#      - class
#
# Input:
#   bioinformatics/amr_results/Transit_5M/sam/
#
# Expected input files:
#   <City>_vs_MEGARes.sam
#
# Output:
#   bioinformatics/amr_results/Transit_5M/tables/<City>/
#
# Output files per city:
#   <City>_gene.tsv
#   <City>_group.tsv
#   <City>_mechanism.tsv
#   <City>_class.tsv
#
# Gene-fraction threshold:
#   -t 80
#
# Notes:
#   ResistomeAnalyzer outputs raw aligned-read counts after applying
#   the gene-fraction threshold. These outputs are later converted to
#   binary presence/absence matrices for qualitative downstream analysis.
#
#   MEGARes database files and the ResistomeAnalyzer executable are not
#   included in GitHub. Users should download/build them separately and
#   update the paths below if needed.
# ============================================================

# ============================================================
# USER SETTINGS
# ============================================================

PROJECT_ROOT="${PROJECT_ROOT:-$HOME/Thesis_AMR_Project}"

SAM_DIR="${SAM_DIR:-$PROJECT_ROOT/bioinformatics/amr_results/Transit_5M/sam}"

OUT_DIR="${OUT_DIR:-$PROJECT_ROOT/bioinformatics/amr_results/Transit_5M}"
TABLE_DIR="$OUT_DIR/tables"
LOG_DIR="$OUT_DIR/logs"
SUMMARY_DIR="$OUT_DIR/summary"

SUMMARY_FILE="$SUMMARY_DIR/transit_resistomeanalyzer_geneFrac80_summary.tsv"

# MEGARes v3.00 files
MEGARES_FASTA="${MEGARES_FASTA:-$PROJECT_ROOT/bioinformatics/amr_db/megares/index/megares_database_v3.00.fasta}"
MEGARES_ANNOT="${MEGARES_ANNOT:-$PROJECT_ROOT/bioinformatics/amr_db/annotations/megares_annotations_v3.00.csv}"

# ResistomeAnalyzer executable
RESISTOME_BIN="${RESISTOME_BIN:-$PROJECT_ROOT/bioinformatics/tools/resistomeanalyzer/resistome}"

# Gene-fraction threshold
GENE_FRACTION_THRESHOLD="${GENE_FRACTION_THRESHOLD:-80}"

# If true, existing output tables are overwritten
OVERWRITE="${OVERWRITE:-true}"

# ============================================================
# CREATE OUTPUT DIRECTORIES
# ============================================================

mkdir -p "$TABLE_DIR" "$LOG_DIR" "$SUMMARY_DIR"

# ============================================================
# CHECK INPUTS AND TOOLS
# ============================================================

if [ ! -d "$SAM_DIR" ]; then
    echo "ERROR: SAM directory not found:"
    echo "$SAM_DIR"
    exit 1
fi

if [ ! -f "$MEGARES_FASTA" ]; then
    echo "ERROR: MEGARes FASTA file not found:"
    echo "$MEGARES_FASTA"
    exit 1
fi

if [ ! -f "$MEGARES_ANNOT" ]; then
    echo "ERROR: MEGARes annotation file not found:"
    echo "$MEGARES_ANNOT"
    exit 1
fi

if [ ! -x "$RESISTOME_BIN" ]; then
    echo "ERROR: ResistomeAnalyzer executable not found or not executable:"
    echo "$RESISTOME_BIN"
    echo
    echo "If the file exists but is not executable, run:"
    echo "chmod +x $RESISTOME_BIN"
    exit 1
fi

# ============================================================
# START SUMMARY FILE
# ============================================================

echo -e "City\tSAM_File\tGene_Table\tGroup_Table\tMechanism_Table\tClass_Table\tGene_Fraction_Threshold\tLog_File\tStatus" > "$SUMMARY_FILE"

echo "============================================================"
echo "Transit ARG profiling with ResistomeAnalyzer"
echo "============================================================"
echo "Project root             : $PROJECT_ROOT"
echo "SAM directory            : $SAM_DIR"
echo "Output table directory   : $TABLE_DIR"
echo "Log directory            : $LOG_DIR"
echo "MEGARes FASTA            : $MEGARES_FASTA"
echo "MEGARes annotation       : $MEGARES_ANNOT"
echo "ResistomeAnalyzer        : $RESISTOME_BIN"
echo "Gene-fraction threshold  : $GENE_FRACTION_THRESHOLD"
echo "Overwrite existing       : $OVERWRITE"
echo "Summary file             : $SUMMARY_FILE"
echo "============================================================"
echo

# ============================================================
# FIND SAM FILES
# ============================================================

mapfile -t SAM_FILES < <(
    find "$SAM_DIR" -maxdepth 1 -type f -name "*_vs_MEGARes.sam" | sort
)

if [ "${#SAM_FILES[@]}" -eq 0 ]; then
    echo "ERROR: No SAM files found under:"
    echo "$SAM_DIR"
    echo "Expected files like: <City>_vs_MEGARes.sam"
    exit 1
fi

echo "SAM files found: ${#SAM_FILES[@]}"
echo

# ============================================================
# PROCESS EACH CITY
# ============================================================

for SAM_FILE in "${SAM_FILES[@]}"; do
    SAM_BASENAME="$(basename "$SAM_FILE")"
    CITY="${SAM_BASENAME%_vs_MEGARes.sam}"

    echo "------------------------------------------------------------"
    echo "Processing city: $CITY"
    echo "------------------------------------------------------------"

    CITY_TABLE_DIR="$TABLE_DIR/$CITY"
    mkdir -p "$CITY_TABLE_DIR"

    GENE_FP="$CITY_TABLE_DIR/${CITY}_gene.tsv"
    GROUP_FP="$CITY_TABLE_DIR/${CITY}_group.tsv"
    CLASS_FP="$CITY_TABLE_DIR/${CITY}_class.tsv"
    MECH_FP="$CITY_TABLE_DIR/${CITY}_mechanism.tsv"

    LOG_FILE="$LOG_DIR/${CITY}_resistomeanalyzer_geneFrac80.log"

    if [ "$OVERWRITE" != "true" ] && \
       [ -f "$GENE_FP" ] && \
       [ -f "$GROUP_FP" ] && \
       [ -f "$CLASS_FP" ] && \
       [ -f "$MECH_FP" ]; then

        echo "Skipping $CITY because all output tables already exist."
        echo

        echo -e "${CITY}\t${SAM_FILE}\t${GENE_FP}\t${GROUP_FP}\t${MECH_FP}\t${CLASS_FP}\t${GENE_FRACTION_THRESHOLD}\t${LOG_FILE}\tSKIPPED_EXISTING" >> "$SUMMARY_FILE"
        continue
    fi

    echo "SAM file        : $SAM_FILE"
    echo "Gene table      : $GENE_FP"
    echo "Group table     : $GROUP_FP"
    echo "Mechanism table : $MECH_FP"
    echo "Class table     : $CLASS_FP"
    echo "Log file        : $LOG_FILE"
    echo

    echo "Running ResistomeAnalyzer with ${GENE_FRACTION_THRESHOLD}% gene-fraction threshold..."

    "$RESISTOME_BIN" \
        -ref_fp "$MEGARES_FASTA" \
        -sam_fp "$SAM_FILE" \
        -annot_fp "$MEGARES_ANNOT" \
        -gene_fp "$GENE_FP" \
        -group_fp "$GROUP_FP" \
        -class_fp "$CLASS_FP" \
        -mech_fp "$MECH_FP" \
        -t "$GENE_FRACTION_THRESHOLD" \
        > "$LOG_FILE" 2>&1

    if [ $? -eq 0 ]; then
        STATUS="SUCCESS"
        echo "Finished ResistomeAnalyzer profiling for $CITY."
    else
        STATUS="FAILED"
        echo "WARNING: ResistomeAnalyzer failed for $CITY. Check log:"
        echo "$LOG_FILE"
    fi

    echo -e "${CITY}\t${SAM_FILE}\t${GENE_FP}\t${GROUP_FP}\t${MECH_FP}\t${CLASS_FP}\t${GENE_FRACTION_THRESHOLD}\t${LOG_FILE}\t${STATUS}" >> "$SUMMARY_FILE"
    echo
done

echo "============================================================"
echo "Transit ARG profiling completed."
echo "============================================================"
echo "Output tables:"
echo "$TABLE_DIR"
echo
echo "Logs:"
echo "$LOG_DIR"
echo
echo "Summary table:"
echo "$SUMMARY_FILE"
echo "============================================================"
